### ISSUE TITLE
如何与electron-builder结合使用

### ISSUE THREAD

**Issue by zhiying8710** [toyobayashi/electron-asar-encrypt-demo#2]
我现在是通过electron-builder打的安装包, 怎么跟它结合到一起使用

**Comment by toyobayashi** [comment]
@zhiying8710 与用什么打包工具无关，只要按照本仓库演示的原理，甚至加密方法用其他的也行，禁用contextIsolation启用nodeIntegration不用preload脚本，编译出原生模块来，加载路径和方法是正确的就可以了。electron-builder 有个 asar.asarUnpack 配置，把原生模块排除出asar包

**Comment by zhiying8710** [comment]
@toyobayashi 我不懂的地方在于`pack.js`怎么在`package.json`里写能让`electron-builder`通过它打asar包

**Comment by toyobayashi** [comment]
@zhiying8710 翻了一圈文档确实没有找到怎么做asar transform。不过你可以试试不用electron-builder自带的打包流程，你自己先打好asar再拷进最后的resources目录里看行不行，我没用过electron-builder。electron-packager是支持自定义asar的

**Comment by zhiying8710** [comment]
@toyobayashi 好的, 感谢, 我去那边提issue

**Comment by zhiying8710** [comment]
https://jolly-roentgen-9c9aba.netlify.app/configuration/configuration.html#beforepack
这个配置可能可以达到目的

**Comment by toyobayashi** [comment]
@zhiying8710 看了下electron-builder的源码，他们没用官方的asar，而是重写了asar打包，没有自定义transform的功能，所以只能试试他们的钩子了，还是得自己打包
