### ISSUE TITLE
Can I use parts of your code? What license?

### ISSUE THREAD

**Issue by sleeyax** [toyobayashi/electron-asar-encrypt-demo#3]
I'm building an encryption module for https://github.com/sleeyax/asarmor that uses parts of your code but I just realized this repository doesn't include a license. Do I have your permission to use parts of your code? Or do you plan to  add a license soon (MIT license would be great)?  Either way, I'll add proper credits back to this repository, of course!

**Comment by toyobayashi** [comment]
@sleeyax 
Of course! It's my pleasure to contribute my code to community. I will add MIT license to this repo.

If you want to integrate this to asarmor, is it better to let user to decide what algorithm to use? 

By the way, the solution described in this repo still has many limitations to code protection, I have no enough confidence to say it is ready for production. Hope you can make it nicer!

Sorry for my bad English.

**Comment by sleeyax** [comment]
Awesome!

> If you want to integrate this to asarmor, is it better to let user to decide what algorithm to use?

For now I'm integrating basic encryption only,  based on your repo's source code. But if users could customise it further at some point that would be a very nice addition! 

The current integration is nearly done (mostly requires more testing before releasing a non-beta version). Check asarmor's README to see how I integrated your demo code at the moment. 

I'm not very proficient in C++ myself. So feel free to contribute to asarmor if you want to, I would appreciate your help very much :)

And your English is alright. If you're having issues understanding me try https://deepl.com translator.

**Comment by toyobayashi** [comment]
Thanks for the acknowledgement! I will take a look at asarmor. Close this issue
