### ISSUE TITLE
最终 js 都可以通过手段获取到的

### ISSUE THREAD

**Issue by Hiymit90** [toyobayashi/electron-asar-encrypt-demo#6]
最终 js 都可以通过手段获取到的

_Originally posted by @HppZ in https://github.com/toyobayashi/electron-asar-encrypt-demo/issues/5#issuecomment-1190409556_

**Comment by toyobayashi** [comment]
没有办法做到完全隐藏JS，打个断点v8就能把所有js dump出来，请仔细阅读readme了解这个仓库的意义
